### ISSUE TITLE
[Question] Is it possible to get a list of commits for a specific branch in a repo?

### ISSUE THREAD

**Issue by bhavik3jain** [cdancy/bitbucket-rest#193]
The title pretty much asks the question.

I am currently trying to create a script, but that requires that I get a list of commits from a repo, but for a specific branch. I tried many different approaches, but was unable to get anywhere. If anyone could give me a pointer it will be very much appreciated.

**Comment by cdancy** [comment]
Checkout [THIS](https://github.com/cdancy/bitbucket-rest/blob/master/src/main/java/com/cdancy/bitbucket/rest/features/CommitsApi.java#L75) Api the documentation for which can be found [HERE](https://docs.atlassian.com/bitbucket-server/rest/6.2.0/bitbucket-rest.html#idp189). You should be able to supply the `since` argument with the branch name to get what you want.

**Comment by bhavik3jain** [comment]
This was perfect. It answers my question and I am able to get the result that I needed. Thanks!
